/*
* Copyright 2015 MICRORISC s.r.o.
* Copyright 2018 IQRF Tech s.r.o.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_microrisc_spi_SimpleSPI_Master */

#ifndef _Included_com_microrisc_spi_SimpleSPI_Master
#define _Included_com_microrisc_spi_SimpleSPI_Master
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_microrisc_spi_SimpleSPI_Master
 * Method:    stub_initialize
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_microrisc_spi_SimpleSPI_1Master_stub_1initialize
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_microrisc_spi_SimpleSPI_Master
 * Method:    stub_getSlaveStatus
 * Signature: ()Lcom/microrisc/spi/SPI_Status;
 */
JNIEXPORT jobject JNICALL Java_com_microrisc_spi_SimpleSPI_1Master_stub_1getSlaveStatus
  (JNIEnv *, jobject);

/*
 * Class:     com_microrisc_spi_SimpleSPI_Master
 * Method:    stub_sendData
 * Signature: ([S)V
 */
JNIEXPORT void JNICALL Java_com_microrisc_spi_SimpleSPI_1Master_stub_1sendData
  (JNIEnv *, jobject, jshortArray);

/*
 * Class:     com_microrisc_spi_SimpleSPI_Master
 * Method:    stub_readData
 * Signature: (I)[S
 */
JNIEXPORT jshortArray JNICALL Java_com_microrisc_spi_SimpleSPI_1Master_stub_1readData
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_microrisc_spi_SimpleSPI_Master
 * Method:    stub_destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_microrisc_spi_SimpleSPI_1Master_stub_1destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
